CI12

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -24,6 +24,11 @@ jobs:
             python3 -m pip install --upgrade pip
             pip install -r requirements.txt
 
+      - name: Check DVC
+        run: | 
+          which dvc || echo 'dvc not found'
+          dvc --version || true
+
       - name: Run Unit Tests
         run: pytest tests/unit
 
